name: docker-sjasmplus

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron:  "0 7 * * 4"
  workflow_dispatch:

jobs:
  image:
    name: docker-sjasmplus
    runs-on: ubuntu-20.04
    strategy:
      # max-parallel: 8
      fail-fast: false
      matrix:
        arch_type:
          - "linux/amd64"
          - "linux/386"
          - "linux/arm64"
          - "linux/ppc64le"
          - "linux/s390x"
          - "linux/arm/v7"
          - "linux/arm/v6"
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "🛠️ Docker QEMU"
        run: make qemu
      - name: "🛠️ Build and 📤 Upload to hub.docker.com"
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            make ${{ matrix.arch_type }} 
      - name: "🧹 Clean"
        run: make clean
      